const BASE=window.QUESTIONS||[]; const CATS=["컴퓨터 기초이론","하드웨어 시스템","시스템 SW 및 응용 SW","컴퓨터 통신 및 네트워크","시스템보안","컴퓨터 시스템 평가","법규·정책·표준","최신 기술 동향","미분류"];
const KEY="comsiStudyUserV1"; let user=JSON.parse(localStorage.getItem(KEY)||"{}"); let currentId=null; let quizOrder=[],quizIndex=-1,quizCorrect=0,quizLocked=false;
const $=id=>document.getElementById(id); const merged=q=>({...q,...(user[q.id]||{})}); const all=()=>BASE.map(merged); function save(){localStorage.setItem(KEY,JSON.stringify(user)); refreshHome();}
function gotoPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='questions')renderQuestions();if(id==='stats')renderStats();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>gotoPage(b.dataset.page)); document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>gotoPage(b.dataset.go));
function counts(data){let m={};data.forEach(q=>m[q.category]=(m[q.category]||0)+1);return m} function renderBars(el,data){let c=counts(data),max=Math.max(1,...Object.values(c));el.innerHTML=Object.entries(c).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar-row"><span>${k}</span><div class="bar-bg"><div class="bar-fill" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join('')||'<div class="muted">데이터 없음</div>'}
function refreshHome(){let d=all();$('qCount').textContent=d.length;$('favCount').textContent=d.filter(q=>q.favorite).length;$('answerCount').textContent=d.filter(q=>q.modelAnswer||q.myAnswer).length;$('quizScore').textContent=localStorage.getItem('quizScore')||'-';renderBars($('homeBars'),d)}
function initFilters(){let rounds=[...new Set(BASE.map(q=>q.round))].sort((a,b)=>b-a);for(let id of ['roundFilter','statsRound']){let s=$(id);rounds.forEach(r=>s.insertAdjacentHTML('beforeend',`<option value="${r}">${r}회</option>`))}CATS.forEach(c=>{$('catFilter').insertAdjacentHTML('beforeend',`<option>${c}</option>`);$('editCategory').insertAdjacentHTML('beforeend',`<option>${c}</option>`)})}
function renderQuestions(){let s=$('search').value.trim().toLowerCase(),r=$('roundFilter').value,se=$('sessionFilter').value,c=$('catFilter').value;let d=all().filter(q=>(!s||q.text.toLowerCase().includes(s))&&(!r||q.round==r)&&(!se||q.session==se)&&(!c||q.category===c));$('resultInfo').textContent=`${d.length}개 문제`;$('questionList').innerHTML=d.slice(0,300).map(q=>`<div class="qitem" data-id="${q.id}"><div class="qtop"><span><b>${q.round}회 ${q.session}교시 ${q.number}번</b> ${q.favorite?'<span class="star">★</span>':''}</span><span class="tag">${q.category}</span></div><div class="qtext">${escapeHtml(q.text)}</div></div>`).join('')+(d.length>300?'<div class="notice">검색 결과가 많아 300개까지만 표시했습니다. 검색/필터를 사용하세요.</div>':'');document.querySelectorAll('.qitem').forEach(x=>x.onclick=()=>openDetail(x.dataset.id))}
['search','roundFilter','sessionFilter','catFilter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderQuestions));
function escapeHtml(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function openDetail(id){let q=all().find(x=>x.id===id);if(!q)return;currentId=id;$('modalMeta').textContent=`제${q.round}회 · ${q.session}교시 · ${q.number}번`;$('modalTitle').textContent=q.category;$('modalQuestion').textContent=q.text;$('editCategory').value=q.category;$('editFavorite').checked=!!q.favorite;$('editModel').value=q.modelAnswer||'';$('editMine').value=q.myAnswer||'';$('editMemo').value=q.memo||'';$('modal').classList.add('open')}
$('closeModal').onclick=()=>$('modal').classList.remove('open');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('open')};$('saveDetail').onclick=()=>{user[currentId]={...(user[currentId]||{}),category:$('editCategory').value,favorite:$('editFavorite').checked,modelAnswer:$('editModel').value,myAnswer:$('editMine').value,memo:$('editMemo').value};save();$('modal').classList.remove('open');renderQuestions()};
function renderStats(){let d=all();renderBars($('statsBars'),d);let r=$('statsRound').value;renderBars($('roundBars'),r?d.filter(q=>q.round==r):d)}$('statsRound').onchange=renderStats;
function newQuiz(){quizOrder=[...Array(QUIZ_BANK.length).keys()].sort(()=>Math.random()-.5);quizIndex=-1;quizCorrect=0;nextQuiz()} function nextQuiz(){quizIndex++;quizLocked=false;$('quizExplain').textContent='';if(quizIndex>=quizOrder.length){let pct=Math.round(quizCorrect/quizOrder.length*100);$('quizQ').textContent=`완료! ${quizCorrect}/${quizOrder.length} (${pct}%)`;$('quizProgress').textContent='';$('quizChoices').innerHTML='';$('quizNext').textContent='다시 시작';localStorage.setItem('quizScore',pct+'%');refreshHome();quizIndex=-1;return}let q=QUIZ_BANK[quizOrder[quizIndex]];$('quizProgress').textContent=`${quizIndex+1} / ${quizOrder.length}`;$('quizQ').textContent=q.q;$('quizChoices').innerHTML=q.choices.map((c,i)=>`<button class="choice" data-i="${i}">${i+1}. ${c}</button>`).join('');$('quizNext').textContent='다음 문제';$('quizNext').style.display='none';document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answerQuiz(+b.dataset.i))}function answerQuiz(i){if(quizLocked)return;quizLocked=true;let q=QUIZ_BANK[quizOrder[quizIndex]];document.querySelectorAll('.choice').forEach((b,j)=>{if(j===q.a)b.classList.add('correct');else if(j===i)b.classList.add('wrong')});if(i===q.a)quizCorrect++;$('quizExplain').textContent=q.ex;$('quizNext').style.display='inline-block'}$('quizNext').onclick=()=>quizIndex===-1?newQuiz():nextQuiz();
$('exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(user,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='comsi-study-backup.json';a.click();URL.revokeObjectURL(a.href)};$('importInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{user=JSON.parse(rd.result);save();alert('복원이 완료되었습니다.')}catch{alert('올바른 백업 파일이 아닙니다.')}};rd.readAsText(f)};$('resetBtn').onclick=()=>{if(confirm('내가 수정한 분류/답안/메모/즐겨찾기를 모두 삭제할까요?')){user={};save();renderQuestions();}};
$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dark',document.body.classList.contains('dark')?'1':'0')};if(localStorage.getItem('dark')==='1')document.body.classList.add('dark');
initFilters();refreshHome();renderQuestions();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js');